// service?y=2022&v=401 (in chrome dev tools)
const data = [
    {
        "team_nbr": 30364,
        "name": "Maryland",
        "web": "",
        "logo": "",
        "gp": 12,
        "gf": 224,
        "ga": 115,
        "wins": 12,
        "losses": 0,
        "ties": 0,
        "agd": 7.66,
        "sched": 92.32,
        "rating": 99.99,
        "adj_average": 0.357,
        "state": "MD",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 1
    },
    {
        "team_nbr": 30231,
        "name": "Georgetown",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 218,
        "ga": 112,
        "wins": 13,
        "losses": 1,
        "ties": 0,
        "agd": 6.57,
        "sched": 90.88,
        "rating": 97.46,
        "adj_average": 0.814,
        "state": "DC",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 2
    },
    {
        "team_nbr": 30456,
        "name": "Notre Dame",
        "web": "",
        "logo": "",
        "gp": 11,
        "gf": 161,
        "ga": 107,
        "wins": 7,
        "losses": 4,
        "ties": 0,
        "agd": 3.27,
        "sched": 92.63,
        "rating": 95.902,
        "adj_average": 0.373,
        "state": "IN",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 3
    },
    {
        "team_nbr": 30177,
        "name": "Duke",
        "web": "",
        "logo": "",
        "gp": 16,
        "gf": 248,
        "ga": 174,
        "wins": 11,
        "losses": 5,
        "ties": 0,
        "agd": 4.62,
        "sched": 91.24,
        "rating": 95.865,
        "adj_average": 0.084,
        "state": "NC",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 4
    },
    {
        "team_nbr": 30688,
        "name": "Virginia",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 222,
        "ga": 163,
        "wins": 11,
        "losses": 3,
        "ties": 0,
        "agd": 4.07,
        "sched": 91.28,
        "rating": 95.352,
        "adj_average": 0.192,
        "state": "VA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 5
    },
    {
        "team_nbr": 30500,
        "name": "Princeton",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 203,
        "ga": 153,
        "wins": 9,
        "losses": 4,
        "ties": 0,
        "agd": 3.07,
        "sched": 91.69,
        "rating": 94.774,
        "adj_average": 0.177,
        "state": "NJ",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 6
    },
    {
        "team_nbr": 30475,
        "name": "Ohio State",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 200,
        "ga": 159,
        "wins": 10,
        "losses": 4,
        "ties": 0,
        "agd": 2.78,
        "sched": 91.18,
        "rating": 93.965,
        "adj_average": 0.155,
        "state": "OH",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 7
    },
    {
        "team_nbr": 30544,
        "name": "Rutgers",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 216,
        "ga": 153,
        "wins": 12,
        "losses": 2,
        "ties": 0,
        "agd": 3.64,
        "sched": 90.09,
        "rating": 93.734,
        "adj_average": 0.129,
        "state": "NJ",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 8
    },
    {
        "team_nbr": 30485,
        "name": "Penn",
        "web": "",
        "logo": "",
        "gp": 12,
        "gf": 155,
        "ga": 138,
        "wins": 8,
        "losses": 4,
        "ties": 0,
        "agd": 1.41,
        "sched": 91.99,
        "rating": 93.411,
        "adj_average": 0,
        "state": "PA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 9
    },
    {
        "team_nbr": 30072,
        "name": "Brown",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 192,
        "ga": 154,
        "wins": 10,
        "losses": 4,
        "ties": 0,
        "agd": 2.57,
        "sched": 90.35,
        "rating": 92.924,
        "adj_average": 0,
        "state": "RI",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 10
    },
    {
        "team_nbr": 30061,
        "name": "Boston University",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 193,
        "ga": 147,
        "wins": 10,
        "losses": 4,
        "ties": 0,
        "agd": 3.21,
        "sched": 89.52,
        "rating": 92.737,
        "adj_average": 0,
        "state": "MA",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 11
    },
    {
        "team_nbr": 30737,
        "name": "Yale",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 202,
        "ga": 168,
        "wins": 10,
        "losses": 3,
        "ties": 0,
        "agd": 2.07,
        "sched": 90.65,
        "rating": 92.732,
        "adj_average": 0,
        "state": "CT",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 12
    },
    {
        "team_nbr": 30140,
        "name": "Cornell",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 187,
        "ga": 163,
        "wins": 11,
        "losses": 3,
        "ties": 0,
        "agd": 1.71,
        "sched": 90.9,
        "rating": 92.615,
        "adj_average": 0,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 13
    },
    {
        "team_nbr": 30524,
        "name": "Richmond",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 193,
        "ga": 130,
        "wins": 9,
        "losses": 4,
        "ties": 0,
        "agd": 3.46,
        "sched": 88.95,
        "rating": 92.418,
        "adj_average": 0.85,
        "state": "VA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 14
    },
    {
        "team_nbr": 30252,
        "name": "Harvard",
        "web": "",
        "logo": "",
        "gp": 12,
        "gf": 162,
        "ga": 140,
        "wins": 8,
        "losses": 4,
        "ties": 0,
        "agd": 1.58,
        "sched": 90.81,
        "rating": 92.399,
        "adj_average": 0.237,
        "state": "MA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 15
    },
    {
        "team_nbr": 30286,
        "name": "Jacksonville",
        "web": "",
        "logo": "",
        "gp": 15,
        "gf": 251,
        "ga": 131,
        "wins": 13,
        "losses": 2,
        "ties": 0,
        "agd": 5.13,
        "sched": 87.26,
        "rating": 92.395,
        "adj_average": 0.909,
        "state": "FL",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 16
    },
    {
        "team_nbr": 30684,
        "name": "Vermont",
        "web": "",
        "logo": "",
        "gp": 15,
        "gf": 201,
        "ga": 133,
        "wins": 9,
        "losses": 6,
        "ties": 0,
        "agd": 4.2,
        "sched": 87.8,
        "rating": 92.003,
        "adj_average": 0.177,
        "state": "VT",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 17
    },
    {
        "team_nbr": 30031,
        "name": "Army",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 201,
        "ga": 152,
        "wins": 11,
        "losses": 3,
        "ties": 0,
        "agd": 3.21,
        "sched": 88.76,
        "rating": 91.976,
        "adj_average": 0.173,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 18
    },
    {
        "team_nbr": 30163,
        "name": "Denver",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 192,
        "ga": 157,
        "wins": 9,
        "losses": 5,
        "ties": 0,
        "agd": 1.92,
        "sched": 89.96,
        "rating": 91.889,
        "adj_average": 0,
        "state": "CO",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 19
    },
    {
        "team_nbr": 30386,
        "name": "Michigan",
        "web": "",
        "logo": "",
        "gp": 15,
        "gf": 211,
        "ga": 167,
        "wins": 7,
        "losses": 8,
        "ties": 0,
        "agd": 1.86,
        "sched": 89.41,
        "rating": 91.281,
        "adj_average": 0,
        "state": "MI",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 20
    },
    {
        "team_nbr": 30654,
        "name": "North Carolina",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 162,
        "ga": 180,
        "wins": 8,
        "losses": 6,
        "ties": 0,
        "agd": -1.14,
        "sched": 92.39,
        "rating": 91.254,
        "adj_average": 0,
        "state": "NC",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 21
    },
    {
        "team_nbr": 30686,
        "name": "Villanova",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 172,
        "ga": 147,
        "wins": 8,
        "losses": 5,
        "ties": 0,
        "agd": 1.69,
        "sched": 89.52,
        "rating": 91.214,
        "adj_average": 0,
        "state": "PA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 22
    },
    {
        "team_nbr": 30289,
        "name": "Johns Hopkins",
        "web": "",
        "logo": "",
        "gp": 15,
        "gf": 164,
        "ga": 186,
        "wins": 7,
        "losses": 8,
        "ties": 0,
        "agd": -1.06,
        "sched": 92.26,
        "rating": 91.202,
        "adj_average": 0,
        "state": "MD",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 23
    },
    {
        "team_nbr": 30337,
        "name": "Loyola",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 174,
        "ga": 172,
        "wins": 8,
        "losses": 7,
        "ties": 0,
        "agd": 0.2,
        "sched": 91.24,
        "rating": 91.173,
        "adj_average": 0,
        "state": "MD",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 24
    },
    {
        "team_nbr": 30588,
        "name": "Saint Josephs PA",
        "web": "",
        "logo": "",
        "gp": 15,
        "gf": 210,
        "ga": 153,
        "wins": 12,
        "losses": 3,
        "ties": 0,
        "agd": 3.6,
        "sched": 86.78,
        "rating": 90.389,
        "adj_average": 0,
        "state": "PA",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 25
    },
    {
        "team_nbr": 30321,
        "name": "Lehigh",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 159,
        "ga": 134,
        "wins": 8,
        "losses": 6,
        "ties": 0,
        "agd": 1.78,
        "sched": 88.89,
        "rating": 90.352,
        "adj_average": 0,
        "state": "PA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 26
    },
    {
        "team_nbr": 30643,
        "name": "Massachusetts",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 157,
        "ga": 138,
        "wins": 8,
        "losses": 5,
        "ties": 0,
        "agd": 1.3,
        "sched": 89.03,
        "rating": 90.338,
        "adj_average": 0,
        "state": "MA",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 27
    },
    {
        "team_nbr": 30616,
        "name": "Syracuse",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 187,
        "ga": 206,
        "wins": 4,
        "losses": 10,
        "ties": 0,
        "agd": -1.85,
        "sched": 92.18,
        "rating": 90.327,
        "adj_average": 0,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 28
    },
    {
        "team_nbr": 30667,
        "name": "Utah",
        "web": "",
        "logo": "",
        "gp": 12,
        "gf": 158,
        "ga": 129,
        "wins": 9,
        "losses": 3,
        "ties": 0,
        "agd": 2.08,
        "sched": 88.2,
        "rating": 90.286,
        "adj_average": 0,
        "state": "UT",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 29
    },
    {
        "team_nbr": 30258,
        "name": "High Point",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 195,
        "ga": 167,
        "wins": 7,
        "losses": 7,
        "ties": 0,
        "agd": 1.42,
        "sched": 88.78,
        "rating": 90.213,
        "adj_average": 0.632,
        "state": "NC",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 30
    },
    {
        "team_nbr": 30077,
        "name": "Bucknell",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 203,
        "ga": 163,
        "wins": 9,
        "losses": 6,
        "ties": 0,
        "agd": 1.86,
        "sched": 87.56,
        "rating": 89.849,
        "adj_average": 0,
        "state": "PA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 31
    },
    {
        "team_nbr": 30504,
        "name": "Penn State",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 157,
        "ga": 191,
        "wins": 3,
        "losses": 11,
        "ties": 0,
        "agd": -2.35,
        "sched": 92.11,
        "rating": 89.76,
        "adj_average": -0.016,
        "state": "PA",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 32
    },
    {
        "team_nbr": 30157,
        "name": "Delaware",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 187,
        "ga": 166,
        "wins": 9,
        "losses": 5,
        "ties": 0,
        "agd": 1.42,
        "sched": 87.95,
        "rating": 89.38,
        "adj_average": 0,
        "state": "DE",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 33
    },
    {
        "team_nbr": 30074,
        "name": "Bryant",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 176,
        "ga": 144,
        "wins": 8,
        "losses": 6,
        "ties": 0,
        "agd": 1.85,
        "sched": 87.43,
        "rating": 89.294,
        "adj_average": 0,
        "state": "RI",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 34
    },
    {
        "team_nbr": 30629,
        "name": "Towson",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 156,
        "ga": 169,
        "wins": 6,
        "losses": 8,
        "ties": 0,
        "agd": -0.92,
        "sched": 90.06,
        "rating": 89.137,
        "adj_average": 0,
        "state": "MD",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 35
    },
    {
        "team_nbr": 30433,
        "name": "Navy",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 160,
        "ga": 152,
        "wins": 9,
        "losses": 6,
        "ties": 0,
        "agd": 0.6,
        "sched": 87.98,
        "rating": 89.057,
        "adj_average": 0,
        "state": "MD",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 36
    },
    {
        "team_nbr": 30608,
        "name": "Stony Brook",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 181,
        "ga": 162,
        "wins": 9,
        "losses": 5,
        "ties": 0,
        "agd": 1.35,
        "sched": 87.36,
        "rating": 88.723,
        "adj_average": 0,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 37
    },
    {
        "team_nbr": 30262,
        "name": "Hobart",
        "web": "",
        "logo": "",
        "gp": 11,
        "gf": 155,
        "ga": 138,
        "wins": 6,
        "losses": 5,
        "ties": 0,
        "agd": 1.54,
        "sched": 86.91,
        "rating": 88.456,
        "adj_average": 0,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 38
    },
    {
        "team_nbr": 30008,
        "name": "Air Force",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 160,
        "ga": 144,
        "wins": 8,
        "losses": 6,
        "ties": 0,
        "agd": 1.14,
        "sched": 87.28,
        "rating": 88.428,
        "adj_average": 0,
        "state": "CO",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 39
    },
    {
        "team_nbr": 30532,
        "name": "Robert Morris",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 170,
        "ga": 154,
        "wins": 8,
        "losses": 5,
        "ties": 0,
        "agd": 0.69,
        "sched": 87.19,
        "rating": 87.888,
        "adj_average": 0,
        "state": "PA",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 40
    },
    {
        "team_nbr": 30152,
        "name": "Dartmouth",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 123,
        "ga": 162,
        "wins": 4,
        "losses": 9,
        "ties": 0,
        "agd": -2.46,
        "sched": 90.34,
        "rating": 87.887,
        "adj_average": 0,
        "state": "NH",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 41
    },
    {
        "team_nbr": 30650,
        "name": "UMBC",
        "web": "",
        "logo": "",
        "gp": 11,
        "gf": 120,
        "ga": 112,
        "wins": 5,
        "losses": 6,
        "ties": 0,
        "agd": 0.72,
        "sched": 87.07,
        "rating": 87.801,
        "adj_average": 0,
        "state": "MD",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 42
    },
    {
        "team_nbr": 30127,
        "name": "Colgate",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 126,
        "ga": 155,
        "wins": 4,
        "losses": 9,
        "ties": 0,
        "agd": -2.15,
        "sched": 89.87,
        "rating": 87.723,
        "adj_average": 0,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 43
    },
    {
        "team_nbr": 30173,
        "name": "Drexel",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 162,
        "ga": 169,
        "wins": 6,
        "losses": 7,
        "ties": 0,
        "agd": -0.53,
        "sched": 88.2,
        "rating": 87.671,
        "adj_average": 0,
        "state": "PA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 44
    },
    {
        "team_nbr": 30203,
        "name": "Fairfield",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 193,
        "ga": 187,
        "wins": 7,
        "losses": 7,
        "ties": 0,
        "agd": 0.42,
        "sched": 86.92,
        "rating": 87.353,
        "adj_average": 0,
        "state": "CT",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 45
    },
    {
        "team_nbr": 30331,
        "name": "LIU",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 157,
        "ga": 150,
        "wins": 7,
        "losses": 7,
        "ties": 0,
        "agd": 0.5,
        "sched": 86.85,
        "rating": 87.35,
        "adj_average": 0,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 46
    },
    {
        "team_nbr": 30358,
        "name": "Marquette",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 152,
        "ga": 179,
        "wins": 4,
        "losses": 10,
        "ties": 0,
        "agd": -1.92,
        "sched": 89.14,
        "rating": 87.22,
        "adj_average": -0.017,
        "state": "WI",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 47
    },
    {
        "team_nbr": 30056,
        "name": "Binghamton",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 143,
        "ga": 155,
        "wins": 5,
        "losses": 8,
        "ties": 0,
        "agd": -0.69,
        "sched": 87.34,
        "rating": 86.654,
        "adj_average": 0,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 48
    },
    {
        "team_nbr": 30264,
        "name": "Hofstra",
        "web": "",
        "logo": "",
        "gp": 15,
        "gf": 150,
        "ga": 165,
        "wins": 6,
        "losses": 9,
        "ties": 0,
        "agd": -1,
        "sched": 87.43,
        "rating": 86.431,
        "adj_average": 0,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 49
    },
    {
        "team_nbr": 30307,
        "name": "Lafayette",
        "web": "",
        "logo": "",
        "gp": 15,
        "gf": 181,
        "ga": 220,
        "wins": 4,
        "losses": 11,
        "ties": 0,
        "agd": -2.46,
        "sched": 88.74,
        "rating": 86.276,
        "adj_average": 0,
        "state": "PA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 50
    },
    {
        "team_nbr": 30011,
        "name": "Albany",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 148,
        "ga": 197,
        "wins": 5,
        "losses": 9,
        "ties": 0,
        "agd": -2.92,
        "sched": 88.85,
        "rating": 85.928,
        "adj_average": -0.29,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 51
    },
    {
        "team_nbr": 30502,
        "name": "Providence",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 155,
        "ga": 198,
        "wins": 6,
        "losses": 8,
        "ties": 0,
        "agd": -2.57,
        "sched": 88.21,
        "rating": 85.643,
        "adj_average": -0.129,
        "state": "RI",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 52
    },
    {
        "team_nbr": 30582,
        "name": "St Bonaventure",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 142,
        "ga": 116,
        "wins": 10,
        "losses": 3,
        "ties": 0,
        "agd": 1.46,
        "sched": 83.93,
        "rating": 85.395,
        "adj_average": 0.31,
        "state": "NY",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 53
    },
    {
        "team_nbr": 30381,
        "name": "Merrimack",
        "web": "",
        "logo": "",
        "gp": 12,
        "gf": 116,
        "ga": 129,
        "wins": 6,
        "losses": 6,
        "ties": 0,
        "agd": -0.91,
        "sched": 86.23,
        "rating": 85.32,
        "adj_average": 0,
        "state": "MA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 54
    },
    {
        "team_nbr": 30354,
        "name": "Marist",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 137,
        "ga": 174,
        "wins": 7,
        "losses": 7,
        "ties": 0,
        "agd": -2.21,
        "sched": 86.87,
        "rating": 84.658,
        "adj_average": -0.008,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 55
    },
    {
        "team_nbr": 30047,
        "name": "Bellarmine",
        "web": "",
        "logo": "",
        "gp": 16,
        "gf": 169,
        "ga": 191,
        "wins": 4,
        "losses": 12,
        "ties": 0,
        "agd": -1.68,
        "sched": 86.23,
        "rating": 84.551,
        "adj_average": 0.199,
        "state": "KY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 56
    },
    {
        "team_nbr": 30349,
        "name": "Manhattan",
        "web": "",
        "logo": "",
        "gp": 12,
        "gf": 112,
        "ga": 115,
        "wins": 6,
        "losses": 6,
        "ties": 0,
        "agd": -0.25,
        "sched": 84.75,
        "rating": 84.506,
        "adj_average": -0.113,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 57
    },
    {
        "team_nbr": 30565,
        "name": "Siena",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 143,
        "ga": 147,
        "wins": 6,
        "losses": 8,
        "ties": 0,
        "agd": -0.28,
        "sched": 84.73,
        "rating": 84.451,
        "adj_average": 0,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 58
    },
    {
        "team_nbr": 30421,
        "name": "Mount St Marys",
        "web": "",
        "logo": "",
        "gp": 15,
        "gf": 135,
        "ga": 181,
        "wins": 5,
        "losses": 10,
        "ties": 0,
        "agd": -2.53,
        "sched": 86.18,
        "rating": 83.652,
        "adj_average": -0.101,
        "state": "MD",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 59
    },
    {
        "team_nbr": 30374,
        "name": "Mercer",
        "web": "",
        "logo": "",
        "gp": 15,
        "gf": 157,
        "ga": 207,
        "wins": 5,
        "losses": 10,
        "ties": 0,
        "agd": -3.13,
        "sched": 86.77,
        "rating": 83.64,
        "adj_average": 0.151,
        "state": "GA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 60
    },
    {
        "team_nbr": 30118,
        "name": "Cleveland State",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 142,
        "ga": 164,
        "wins": 3,
        "losses": 10,
        "ties": 0,
        "agd": -1.92,
        "sched": 85.29,
        "rating": 83.368,
        "adj_average": 0.154,
        "state": "OH",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 61
    },
    {
        "team_nbr": 30513,
        "name": "Quinnipiac",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 135,
        "ga": 183,
        "wins": 2,
        "losses": 11,
        "ties": 0,
        "agd": -3.53,
        "sched": 86.19,
        "rating": 82.656,
        "adj_average": -0.207,
        "state": "CT",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 62
    },
    {
        "team_nbr": 30696,
        "name": "Wagner",
        "web": "",
        "logo": "",
        "gp": 12,
        "gf": 88,
        "ga": 121,
        "wins": 3,
        "losses": 9,
        "ties": 0,
        "agd": -2.75,
        "sched": 85.35,
        "rating": 82.606,
        "adj_average": 0,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 63
    },
    {
        "team_nbr": 30402,
        "name": "Monmouth",
        "web": "",
        "logo": "",
        "gp": 12,
        "gf": 87,
        "ga": 122,
        "wins": 5,
        "losses": 7,
        "ties": 0,
        "agd": -2.33,
        "sched": 84.91,
        "rating": 82.582,
        "adj_average": -0.182,
        "state": "NJ",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 64
    },
    {
        "team_nbr": 30547,
        "name": "Sacred Heart",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 137,
        "ga": 190,
        "wins": 3,
        "losses": 10,
        "ties": 0,
        "agd": -3.76,
        "sched": 85.94,
        "rating": 82.171,
        "adj_average": 0,
        "state": "CT",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 65
    },
    {
        "team_nbr": 30266,
        "name": "Holy Cross",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 120,
        "ga": 235,
        "wins": 1,
        "losses": 13,
        "ties": 0,
        "agd": -6.35,
        "sched": 88.42,
        "rating": 82.068,
        "adj_average": 0,
        "state": "MA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 66
    },
    {
        "team_nbr": 30087,
        "name": "Canisius",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 128,
        "ga": 204,
        "wins": 2,
        "losses": 12,
        "ties": 0,
        "agd": -4.64,
        "sched": 86.58,
        "rating": 81.938,
        "adj_average": 0,
        "state": "NY",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 67
    },
    {
        "team_nbr": 30586,
        "name": "St John's",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 125,
        "ga": 257,
        "wins": 2,
        "losses": 12,
        "ties": 0,
        "agd": -6.71,
        "sched": 88.63,
        "rating": 81.924,
        "adj_average": -0.558,
        "state": "NY",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 68
    },
    {
        "team_nbr": 30167,
        "name": "Detroit Mercy",
        "web": "",
        "logo": "",
        "gp": 11,
        "gf": 84,
        "ga": 171,
        "wins": 2,
        "losses": 9,
        "ties": 0,
        "agd": -6.18,
        "sched": 87.97,
        "rating": 81.789,
        "adj_average": -0.571,
        "state": "MI",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 69
    },
    {
        "team_nbr": 30649,
        "name": "Massachusetts-Lowell",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 128,
        "ga": 194,
        "wins": 2,
        "losses": 11,
        "ties": 0,
        "agd": -4.3,
        "sched": 86.09,
        "rating": 81.789,
        "adj_average": -0.063,
        "state": "MA",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 70
    },
    {
        "team_nbr": 30691,
        "name": "VMI",
        "web": "",
        "logo": "",
        "gp": 14,
        "gf": 139,
        "ga": 183,
        "wins": 4,
        "losses": 10,
        "ties": 0,
        "agd": -2.85,
        "sched": 83.71,
        "rating": 80.857,
        "adj_average": -0.109,
        "state": "VA",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 71
    },
    {
        "team_nbr": 30447,
        "name": "NJIT",
        "web": "",
        "logo": "",
        "gp": 13,
        "gf": 90,
        "ga": 193,
        "wins": 0,
        "losses": 13,
        "ties": 0,
        "agd": -7.3,
        "sched": 86.85,
        "rating": 79.55,
        "adj_average": -0.594,
        "state": "NJ",
        "facebook": null,
        "twitter": null,
        "instagram": null,
        "div_rank_live": 1,
        "ranking": 72
    },
    {
        "team_nbr": 30247,
        "name": "Hampton",
        "web": "",
        "logo": "",
        "gp": 10,
        "gf": 47,
        "ga": 209,
        "wins": 0,
        "losses": 10,
        "ties": 0,
        "agd": -9.9,
        "sched": 81.26,
        "rating": 71.363,
        "adj_average": -4.472,
        "state": "VA",
        "facebook": "",
        "twitter": "",
        "instagram": "",
        "div_rank_live": 1,
        "ranking": 73
    }
]

const getLaxNumbersDictionary = () => {
    // console.log('called')
    const laxNumbersDictionary = {};
    data.forEach((teamRank) => laxNumbersDictionary[teamRank.name] = teamRank);
    // console.log('laxNumbersDictionary =', laxNumbersDictionary);
    return laxNumbersDictionary;
};

module.exports = {
    getLaxNumbersDictionary
};

// getLaxNumbersDictionary();

